#!/bin/bash
echo "Vérifiction des librairies python3"
sudo pip3 install -r requirements.txt
sudo pip3 install --upgrade -r requirements.txt
echo "Fin de la vérifiction des librairies python3"
echo "Démarage d'Hervé"
sudo python3 __main__.py run # -h $IP -p $PORT
